version: '3.8'
services:
  e-commerce:
    image: e-commerce:v1.0
    environment:
      - FLASK_CONTEXT=${FLASK_CONTEXT}
      - FLASK_APP=${FLASK_APP}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "3000:3000"
    networks:
      - ecommerce_red
    
networks:
  ecommerce_red:
    external: true  
